## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import os

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_to_load = os.path.join("Weather_DataBase","WeatherPy_DataBase.csv")
city_data_df = pd.read_csv(city_data_to_load)
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Caravelas,BR,-17.7125,-39.2481,77.74,81,80,6.58,broken clouds
1,1,Saint George,US,37.1041,-113.5841,70.54,16,0,1.99,clear sky
2,2,Ushuaia,AR,-54.8000,-68.3000,40.66,81,75,37.98,light rain
3,3,Busselton,AU,-33.6500,115.3333,63.05,77,0,11.48,clear sky
4,4,Marsabit,KE,2.3284,37.9899,71.62,40,11,9.75,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip?"))
max_temp = float(input("What is the maximum temperature you would like for your trip?"))

What is the minimum temperature you would like for your trip?75
What is the maximum temperature you would like for your trip?90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                      (city_data_df["Max Temp"] >= min_temp)]

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                226
City                   226
Country                225
Lat                    226
Lng                    226
Max Temp               226
Humidity               226
Cloudiness             226
Wind Speed             226
Current Description    226
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Caravelas,BR,-17.7125,-39.2481,77.74,81,80,6.58,broken clouds
5,5,Sao Joao Da Barra,BR,-21.6403,-41.0511,80.69,87,8,11.21,clear sky
12,12,Saint-Philippe,RE,-21.3585,55.7679,80.19,87,34,9.28,scattered clouds
15,15,Santa Cruz Do Rio Pardo,BR,-22.8989,-49.6325,80.74,67,40,2.46,scattered clouds
21,21,Rock Sound,BS,24.9000,-76.2000,77.14,80,49,13.22,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
687,687,Cantanhede,BR,-3.6333,-44.3767,76.96,94,77,4.07,moderate rain
693,693,Bodden Town,KY,19.2833,-81.2500,84.99,69,75,4.61,broken clouds
694,694,Breves,BR,-1.6822,-50.4803,78.42,85,91,2.75,overcast clouds
700,700,Terra Santa,BR,-2.1042,-56.4869,82.83,78,86,1.68,overcast clouds
708,708,Jacareacanga,BR,-6.2222,-57.7528,79.68,95,82,0.94,broken clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Caravelas,BR,77.74,broken clouds,-17.7125,-39.2481,
5,Sao Joao Da Barra,BR,80.69,clear sky,-21.6403,-41.0511,
12,Saint-Philippe,RE,80.19,scattered clouds,-21.3585,55.7679,
15,Santa Cruz Do Rio Pardo,BR,80.74,scattered clouds,-22.8989,-49.6325,
21,Rock Sound,BS,77.14,scattered clouds,24.9000,-76.2000,
23,Inirida,CO,85.84,overcast clouds,3.8653,-67.9239,
25,Bambous Virieux,MU,81.21,scattered clouds,-20.3428,57.7575,
31,Riachao Do Jacuipe,BR,83.25,heavy intensity rain,-11.8069,-39.3856,
32,Arraial Do Cabo,BR,80.56,scattered clouds,-22.9661,-42.0278,
33,San Lorenzo,PY,86.94,clear sky,-25.3333,-57.5333,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")

Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[hotel_df["Hotel Name"] != ""]

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0,31.0),zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))